---

- name: Install network tools
  package:
    name:
      - ethtool
      - wpa_supplicant
      - wpa_actiond
      - dhcpcd
      - nmap
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
      - rkhunter propupdate

- name: Enable dhcp service
  service: name=dhcpcd state=started enabled=yes
